# Generated by Django 5.2.6 on 2026-02-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('collector', 'Collector'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
