# Generated by Django 6.0.2 on 2026-02-14 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(choices=[('dry', 'Dry Waste'), ('wet', 'Wet Waste'), ('glass', 'Glass'), ('paper', 'Paper'), ('wood', 'Wood'), ('metal', 'Metal'), ('plastic', 'Plastic')], max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('pickup_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
