# Generated by Django 5.2.6 on 2026-02-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequest',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
