# Generated by Django 5.2.6 on 2026-02-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0004_alter_wasterequest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequest',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='waste_image',
            field=models.ImageField(blank=True, null=True, upload_to='waste_images/'),
        ),
    ]
