# Generated by Django 5.2.6 on 2026-02-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0005_wasterequest_phone_wasterequest_waste_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasterequest',
            name='pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
