# Generated by Django 5.2.6 on 2026-02-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0006_alter_wasterequest_pickup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wasterequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
